<?php

declare(strict_types=1);

namespace App\Controllers;

use Core\Response;
use App\Models\Waiter;

class WaiterController
{
    public function getWaiters(): string
    {
        $waiters = new Waiter()->getAll();

        if (!$waiters) {
            return Response::error('Waiters not found', 404);
        }
        return Response::json($waiters);
    }

    public function createWaiter(): string
    {
        $bodyData = Response::getBodyFromRequest();

        if (!$bodyData) {
            return Response::error('Request body is required', 400);
        }

        $waiterId = new Waiter()->create($bodyData);

        if (!$waiterId) {
            return Response::error('Waiter not created');
        }
        return Response::json("Created successfully (waiter id: " . $waiterId . ")");
    }

    public function updateWaiter(string $id): string
    {
        $bodyData = Response::getBodyFromRequest();

        if (!$bodyData || !$id) {
            return Response::error('Request body and id are required', 400);
        }

        // remove _id from data because it is auto generated by mongodb
        unset($bodyData['_id']);

        $isUpdated = new Waiter()->update($id, $bodyData);

        if (!$isUpdated) {
            return Response::error('Waiter not updated');
        }
        return Response::json("Updated successfully");
    }

    public function deleteWaiter(string $id): string
    {
        if (!$id) {
            return Response::error('Id is required', 400);
        }

        $isDeleted = new Waiter()->delete($id);

        if (!$isDeleted) {
            return Response::error('Waiter not deleted');
        }
        return Response::json("Deleted successfully");
    }
}
